In [1]:
import pandas as pd
import requests
import numpy as np
import statsapi

In [2]:
url = 'http://statsapi.mlb.com/api/v1/schedule/games/?sportId=1'
r = requests.get(url=url).json()
dates = r['dates'][0]['games']
df = pd.DataFrame(dates)
df

,gamePk,gameGuid,link,gameType,season,gameDate,officialDate,status,teams,venue,...,dayNight,scheduledInnings,reverseHomeAwayStatus,inningBreakLength,gamesInSeries,seriesGameNumber,seriesDescription,recordSource,ifNecessary,ifNecessaryDescription
0,745717,107667f4-a7d6-4ee0-91ee-0479bd158455,/api/v1.1/game/745717/feed/live,R,2024,2024-07-22T17:05:00Z,2024-07-22,"{'abstractGameState': 'Final', 'codedGameState...","{'away': {'leagueRecord': {'wins': 50, 'losses...","{'id': 3313, 'name': 'Yankee Stadium', 'link':...",...,day,9,False,120,4,4,Regular Season,S,N,Normal Game
1,746612,2f169a9a-fa83-464b-839f-6c3c4fffc697,/api/v1.1/game/746612/feed/live,R,2024,2024-07-22T22:40:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 49, 'losses...","{'id': 5, 'name': 'Progressive Field', 'link':...",...,night,9,False,120,4,1,Regular Season,S,N,Normal Game
2,745473,bbd9cf73-afa6-4cc5-8785-0a7fa6238609,/api/v1.1/game/745473/feed/live,R,2024,2024-07-22T22:40:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 52, 'losses...","{'id': 31, 'name': 'PNC Park', 'link': '/api/v...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
3,746034,b7941d0e-6c24-4f12-99a1-87af6291683e,/api/v1.1/game/746034/feed/live,R,2024,2024-07-22T22:40:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 50, 'losses...","{'id': 4169, 'name': 'loanDepot park', 'link':...",...,night,9,False,120,4,4,Regular Season,S,N,Normal Game
4,747095,19a90f0e-c8b5-48bd-a0c5-47cd59594361,/api/v1.1/game/747095/feed/live,R,2024,2024-07-22T23:20:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 47, 'losses...","{'id': 4705, 'name': 'Truist Park', 'link': '/...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
5,745881,641f18f1-e96f-4909-9c36-c83030dfcd15,/api/v1.1/game/745881/feed/live,R,2024,2024-07-22T23:40:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 63, 'losses...","{'id': 3312, 'name': 'Target Field', 'link': '...",...,night,9,False,145,3,1,Regular Season,S,N,Normal Game
6,744988,287f47ef-a785-43c2-b8be-d7ed9ce7310f,/api/v1.1/game/744988/feed/live,R,2024,2024-07-23T00:05:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 27, 'losses...","{'id': 5325, 'name': 'Globe Life Field', 'link...",...,night,9,False,120,4,1,Regular Season,S,N,Normal Game
7,746850,0a47bde8-f628-40ed-a06a-0836386b6512,/api/v1.1/game/746850/feed/live,R,2024,2024-07-23T00:05:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 57, 'losses...","{'id': 17, 'name': 'Wrigley Field', 'link': '/...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
8,746280,f4d9f6b4-0bb3-4ae2-9115-c76c02e17aef,/api/v1.1/game/746280/feed/live,R,2024,2024-07-23T00:10:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 51, 'losses...","{'id': 7, 'name': 'Kauffman Stadium', 'link': ...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
9,746526,26fdca47-3cc5-447c-8ec7-b8aa0b06c425,/api/v1.1/game/746526/feed/live,R,2024,2024-07-23T00:40:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 53, 'losses...","{'id': 19, 'name': 'Coors Field', 'link': '/ap...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
10,745635,bb665643-5d2a-407b-a5a7-730a292f6758,/api/v1.1/game/745635/feed/live,R,2024,2024-07-23T01:40:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 52, 'losses...","{'id': 10, 'name': 'Oakland Coliseum', 'link':...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
11,745232,af82149c-a034-4fcc-a2c7-0d97e4758b34,/api/v1.1/game/745232/feed/live,R,2024,2024-07-23T01:40:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 42, 'losses...","{'id': 680, 'name': 'T-Mobile Park', 'link': '...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
12,746124,c40d1955-e314-4701-96ab-72b6ba0de967,/api/v1.1/game/746124/feed/live,R,2024,2024-07-23T02:10:00Z,2024-07-22,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 48, 'losses...","{'id': 22, 'name': 'Dodger Stadium', 'link': '...",...,night,9,False,120,4,1,Regular Season,S,N,Normal Game

In [3]:
HOST = 'https://statsapi.mlb.com'
url = HOST + df.loc[0,'link']
r = requests.get(url=url).json()
player_df = pd.DataFrame(r['gameData']['players'])
player_df_all = pd.DataFrame(['players'])
player_df = player_df.T

player_df

,id,fullName,link,firstName,lastName,primaryNumber,birthDate,currentAge,birthCity,birthStateProvince,...,initLastName,fullFMLName,fullLFMName,strikeZoneTop,strikeZoneBottom,nickName,nameTitle,nameSuffix,pronunciation,nameMatrilineal
ID543859,543859,Michael Tonkin,/api/v1/people/543859,Michael,Tonkin,50,1989-11-19,34,Glendale,CA,...,M Tonkin,Michael Harvey Tonkin,"Tonkin, Michael Harvey",3.756,1.746,NaN,NaN,NaN,NaN,NaN
ID670764,670764,Taylor Walls,/api/v1/people/670764,Taylor,Walls,6,1996-07-10,28,Cordele,GA,...,T Walls,Taylor Walls,"Walls, Taylor",3.46,1.58,NaN,NaN,NaN,NaN,NaN
ID641482,641482,Nestor Cortes,/api/v1/people/641482,Nestor,Cortes,65,1994-12-10,29,Surgidero de Batabano,NaN,...,N Cortes,Nestor Cortes,"Cortes, Nestor",3.319,1.513,Hialeah Kid,Jr.,Jr.,NaN,NaN
ID542888,542888,Shawn Armstrong,/api/v1/people/542888,Shawn,Armstrong,64,1990-09-11,33,New Bern,NC,...,S Armstrong,Shawn Michael Armstrong,"Armstrong, Shawn Michael",3.467,1.589,Armie,NaN,NaN,NaN,NaN
ID518934,518934,DJ LeMahieu,/api/v1/people/518934,David,LeMahieu,26,1988-07-13,36,Visalia,CA,...,D LeMahieu,David John LeMahieu,"LeMahieu, David John",3.31,1.55,Big Fundy,NaN,NaN,luh-MAY-hyoo,NaN
ID664040,664040,Brandon Lowe,/api/v1/people/664040,Brandon,Lowe,8,1994-07-06,30,Suffolk,VA,...,B Lowe,Brandon Norman Lowe,"Lowe, Brandon Norman",3.27,1.52,Bamm-Bamm,NaN,NaN,rhymes with 'now',NaN
ID671737,671737,Taj Bradley,/api/v1/people/671737,Taj,Bradley,45,2001-03-20,23,Los Angeles,CA,...,T Bradley,Taj Ali Bradley,"Bradley, Taj Ali",3.467,1.589,NaN,NaN,NaN,NaN,NaN
ID664126,664126,Pete Fairbanks,/api/v1/people/664126,Peter,Fairbanks,29,1993-12-16,30,Milwaukee,WI,...,P Fairbanks,Peter Anderson Fairbanks,"Fairbanks, Peter Anderson",3.656,1.677,NaN,NaN,NaN,NaN,NaN
ID657077,657077,Alex Verdugo,/api/v1/people/657077,Alexander,Verdugo,24,1996-05-15,28,Tucson,AZ,...,A Verdugo,Alexander Brady Verdugo,"Verdugo, Alexander Brady",3.54,1.6,Dugie,NaN,NaN,vehr-DOO-go,NaN
ID676356,676356,Jonny DeLuca,/api/v1/people/676356,Jonathan,DeLuca,21,1998-07-10,26,Thousand Oaks,CA,...,J DeLuca,Jonathan Davis DeLuca,"DeLuca, Jonathan Davis",3.28,1.56,NaN,NaN,NaN,NaN,NaN
ID669224,669224,Austin Wells,/api/v1/people/669224,Austin,Wells,28,1999-07-12,25,Scottsdale,AZ,...,A Wells,Austin Kenneth Wells,"Wells, Austin Kenneth",3.46,1.62,NaN,NaN,NaN,NaN,NaN
ID700250,700250,Ben Rice,/api/v1/people/700250,Benjamin,Rice,93,1999-02-22,25,Cohasset,MA,...,B Rice,Benjamin Kimball Rice,"Rice, Benjamin Kimball",3.7,1.83,NaN,NaN,NaN,NaN,NaN
ID650402,650402,Gleyber Torres,/api/v1/people/650402,Gleyber,Torres,25,1996-12-13,27,Caracas,NaN,...,G Torres,Gleyber David Torres,"Torres, Gleyber David",3.25,1.53,De Caracas,NaN,NaN,GLAY-burr,Castro
ID670955,670955,Edwin Uceta,/api/v1/people/670955,Edwin,Uceta,63,1998-01-09,26,Villa Los Almacigos,NaN,...,E Uceta,Edwin Daniel Uceta,"Uceta, Edwin Daniel",3.371,1.535,NaN,NaN,NaN,NaN,Martinez
ID664776,664776,Jake Cousins,/api/v1/people/664776,Jake,Cousins,61,1994-07-14,30,Parkridge,IL,...,J Cousins,Jake O. Cousins,"Cousins, Jake O.",3.549,1.627,NaN,NaN,NaN,NaN,NaN
ID605280,605280,Clay Holmes,/api/v1/people/605280,Clayton,Holmes,35,1993-03-27,31,Dothan,AL,...,C Holmes,Clayton Walter Holmes,"Holmes, Clayton Walter",3.575,1.681,NaN,NaN,NaN,NaN,NaN
ID621363,621363,Colin Poche,/api/v1/people/621363,Colin,Poche,38,1994-01-17,30,Flower Mound,TX,...,C Poche,Colin Michael Poche,"Poche, Colin Michael",3.49,1.601,Po,NaN,NaN,poh-SHAY,NaN
ID641793,641793,Zack Littell,/api/v1/people/641793,Zack,Littell,52,1995-10-05,28,Burlington,NC,...,Z Littell,Zack Stuart Littell,"Littell, Zack Stuart",3.549,1.627,Lit,NaN,NaN,lah-TELL,NaN
ID665742,665742,Juan Soto,/api/v1/people/665742,Juan,Soto,22,1998-10-25,25,Santo Domingo,NaN,...,J Soto,Juan Jose Soto,"Soto, Juan Jose",3.1,1.5,Soto Pacheco,NaN,NaN,NaN,Pacheco
ID573186,573186,Marcus Stroman,/api/v1/people/573186,Marcus,Stroman,0,1991-05-01,33,Medford,NY,...,M Stroman,Marcus Earl Stroman,"Stroman, Marcus Earl",3.38,1.56,HDMH,NaN,NaN,NaN,NaN
ID663757,663757,Trent Grisham,/api/v1/people/663757,Trenton,Grisham,12,1996-11-01,27,Burleson,TX,...,T Grisham,Trenton Marcus Grisham,"Grisham, Trenton Marcus",3.66,1.8,Grish,NaN,NaN,GRISH-um,NaN
ID605204,605204,J.D. Davis,/api/v1/people/605204,Jonathan,Davis,38,1993-04-27,31,Elk Grove,CA,...,J Davis,Jonathan Gregory Davis,"Davis, Jonathan Gregory",3.51,1.6,Dizzle,NaN,NaN,NaN,NaN
ID543037,543037,Gerrit Cole,/api/v1/people/543037,Gerrit,Cole,45,1990-09-08,33,Newport Beach,CA,...,G Cole,Gerrit Alan Cole,"Cole, Gerrit Alan",3.549,1.627,Chef G,NaN,NaN,NaN,NaN
ID672782,672782,Yoendrys Gómez,/api/v1/people/672782,Yoendrys,Gómez,92,1999-10-15,24,Nirgua,NaN,...,Y Gómez,Yoendrys Adrian Gómez,"Gómez, Yoendrys Adrian",3.49,1.601,NaN,NaN,NaN,NaN,Perez
ID642350,642350,Jose Siri,/api/v1/people/642350,Jose,Siri,22,1995-07-22,29,Sabana Grande de Boya,NaN,...,J Siri,Jose Alexander Siri,"Siri, Jose Alexander",3.51,1.68,NaN,NaN,NaN,NaN,NaN
ID670623,670623,Isaac Paredes,/api/v1/people/670623,Isaac,Paredes,17,1999-02-18,25,Hermosillo,Sonora,...,I Paredes,Isaac Edgardo Paredes,"Paredes, Isaac Edgardo",3.29,1.59,NaN,NaN,NaN,e-sa-AK Puh-ray-dess,Calderon
ID676604,676604,Tyler Zuber,/api/v1/people/676604,Tyler,Zuber,53,1995-06-16,29,White Hall,AR,...,T Zuber,Tyler Zuber,"Zuber, Tyler",3.319,1.513,NaN,NaN,NaN,NaN,NaN
ID676609,676609,José Caballero,/api/v1/people/676609,José,Caballero,7,1996-08-30,27,Las Tablas,NaN,...,J Caballero,José Caballero,"Caballero, José",3.03,1.38,NaN,NaN,NaN,NaN,NaN
ID666163,666163,Ben Rortvedt,/api/v1/people/666163,Benjamin,Rortvedt,30,1997-09-25,26,Madison,WI,...,B Rortvedt,Benjamin Thomas Rortvedt,"Rortvedt, Benjamin Thomas",3.16,1.5,NaN,NaN,NaN,rort-vet,NaN
ID607074,607074,Carlos Rodón,/api/v1/people/607074,Carlos,Rodón,55,1992-12-10,31,Miami,FL,...,C Rodón,Carlos Antonio Rodón,"Rodón, Carlos Antonio",3.467,1.589,Los,NaN,NaN,row-DON,NaN
ID680700,680700,Richie Palacios,/api/v1/people/680700,Richard,Palacios,1,1997-05-16,27,Brooklyn,NY,...,R Palacios,Richard Palacios,"Palacios, Richard",3.47,1.65,NaN,NaN,NaN,NaN,NaN
ID668227,668227,Randy Arozarena,/api/v1/people/668227,Randy,Arozarena,56,1995-02-28,29,Havana,NaN,...,R Arozarena,Randy Arozarena,"Arozarena, Randy",3.28,1.54,NaN,NaN,NaN,ah-row-sah-RAY-nah,Gonzalez
ID663330,663330,Jahmai Jones,/api/v1/people/663330,Jahmai,Jones,14,1997-08-04,26,Roswell,GA,...,J Jones,Jahmai Fitzgerald Jones,"Jones, Jahmai Fitzgerald",3.49,1.64,NaN,NaN,NaN,juh-MY,NaN
ID669358,669358,Shane Baz,/api/v1/people/669358,Shane,Baz,11,1999-06-17,25,Houston,TX,...,S Baz,Shane Austin Baz,"Baz, Shane Austin",3.467,1.589,NaN,NaN,NaN,BOZ,NaN
ID596133,596133,Luke Weaver,/api/v1/people/596133,Luke,Weaver,30,1993-08-21,30,DeLand,FL,...,L Weaver,Luke Allen Weaver,"Weaver, Luke Allen",3.467,1.589,Dream,NaN,NaN,NaN,NaN
ID592094,592094,Jason Adam,/api/v1/people/592094,Jason,Adam,47,1991-08-04,32,Omaha,NE,...,J Adam,Jason Kendall Adam,"Adam, Jason Kendall",3.49,1.601,NaN,NaN,NaN,NaN,NaN
ID642708,642708,Amed Rosario,/api/v1/people/642708,German,Rosario,10,1995-11-20,28,Santo Domingo Centro,NaN,...,A Rosario,German Amed Rosario,"Rosario, German Amed",3.3,1.57,Rosie,NaN,NaN,row-SAH-ree-oh,Valdez
ID665828,665828,Oswaldo Cabrera,/api/v1/people/665828,Oswaldo,Cabrera,95,1999-03-01,25,Guarenas,NaN,...,O Cabrera,Oswaldo Alberto Cabrera,"Cabrera, Oswaldo Alberto",3.19,1.49,NaN,NaN,NaN,NaN,Mabaricuna
ID592450,592450,Aaron Judge,/api/v1/people/592450,Aaron,Judge,99,1992-04-26,32,Linden,CA,...,A Judge,Aaron James Judge,"Judge, Aaron James",4.05,1.83,Baj,NaN,NaN,NaN,NaN
ID657571,657571,Caleb Ferguson,/api/v1/people/657571,Caleb,Ferguson,64,1996-07-02,28,Columbus,OH,...,C Ferguson,Caleb Paul Ferguson,"Ferguson, Caleb Paul",3.49,1.601,NaN,NaN,NaN,NaN,NaN
ID678554,678554,Curtis Mead,/api/v1/people/678554,Curtis,Mead,25,2000-10-26,23,Adelaide,NaN,...,C Mead,Curtis James Mead,"Mead, Curtis James",3.57,1.67,NaN,NaN,NaN,NaN,NaN
ID657612,657612,Tim Hill,/api/v1/people/657612,Timothy,Hill,54,1990-02-10,34,Mission Hills,CA,...,T Hill,Timothy Hill,"Hill, Timothy",3.549,1.627,Tim Jim,NaN,NaN,NaN,NaN
ID664076,664076,Garrett Cleavinger,/api/v1/people/664076,Garrett,Cleavinger,60,1994-04-23,30,Lawrence,KS,...,G Cleavinger,Garrett J. Cleavinger,"Cleavinger, Garrett J.",3.411,1.565,NaN,NaN,NaN,NaN,NaN
ID687330,687330,Kevin Kelly,/api/v1/people/687330,Kevin,Kelly,49,1997-11-28,26,Springfield,VA,...,K Kelly,Kevin Clayton Kelly,"Kelly, Kevin Clayton",3.467,1.589,NaN,NaN,NaN,NaN,NaN
ID621107,621107,Zach Eflin,/api/v1/people/621107,Zachary,Eflin,24,1994-04-08,30,Orlando,FL,...,Z Eflin,Zachary Adams Eflin,"Eflin, Zachary Adams",3.68,1.7,Ef,NaN,NaN,EFF-lin,NaN
ID666139,666139,Josh Lowe,/api/v1/people/666139,Joshua,Lowe,15,1998-02-02,26,Chesapeake,VA,...,J Lowe,Joshua Edward Lowe,"Lowe, Joshua Edward",3.72,1.78,NaN,NaN,NaN,low,NaN
ID592454,592454,Tommy Kahnle,/api/v1/people/592454,Thomas,Kahnle,41,1989-08-07,34,Latham,NY,...,T Kahnle,Thomas Robert Kahnle,"Kahnle, Thomas Robert",3.411,1.565,King Kahn,NaN,NaN,cain-lee,NaN
ID683011,683011,Anthony Volpe,/api/v1/people/683011,Anthony,Volpe,11,2001-04-28,23,New York,NY,...,A Volpe,Anthony Michael Volpe,"Volpe, Anthony Michael",3.39,1.6,NaN,NaN,NaN,NaN,NaN
ID665966,665966,Carlos Narvaez,/api/v1/people/665966,Carlos,Narvaez,94,1998-11-26,25,Maracay,NaN,...,C Narvaez,Carlos Luis Narvaez,"Narvaez, Carlos Luis",3.319,1.513,NaN,NaN,NaN,NaN,Olivo
ID661563,661563,Luis Gil,/api/v1/people/661563,Luis,Gil,81,1998-06-03,26,Azua,NaN,...,L Gil,Luis Angel Gil,"Gil, Luis Angel",3.467,1.589,NaN,NaN,NaN,Heel,Brito
ID655889,655889,Manuel Rodríguez,/api/v1/people/655889,Manuel,Rodríguez,39,1996-08-06,27,Merida,Yucatan,...,M Rodríguez,Manuel De Jesus Rodríguez,"Rodríguez, Manuel De Jesus",3.319,1.513,NaN,NaN,NaN,NaN,Caamal
ID656577,656577,Alex Jackson,/api/v1/people/656577,Alexander,Jackson,28,1995-12-25,28,San Diego,CA,...,A Jackson,Alexander James Jackson,"Jackson, Alexander James",3.49,1.66,NaN,NaN,NaN,NaN,NaN

In [4]:
def get_avg(player_id):
    player = statsapi.player_stat_data(int(player_id), group= "hitting", type="season", sportId=1)
    if player['position'] == 'P':
        return 0
    return float(player['stats'][0]['stats']['avg'])

def get_atBats(player_id):
    player = statsapi.player_stat_data(int(player_id), group= "hitting", type="season", sportId=1)
    if player['position'] == 'P':
        return 0
    return float(player['stats'][0]['stats']['atBats'])



averages = player_df.id.apply(get_avg)
player_df = player_df.assign(avg=averages.values)

player_atBats = player_df.id.apply(get_atBats)
player_df = player_df.assign(atBats=player_atBats.values)

In [5]:
batScore = player_df.avg * player_df.atBats / 30
player_df = player_df.assign(batScore=batScore.values)

# Why divide by 30 then multiply by the batting average?
# Wouldn't it be easier to simply filter out all players who have not had sufficient at bats to qualify?
# Also...what is the purpose of day score? How does it differ from bat score?

dayScore = player_df.batScore
player_df = player_df.assign(dayScore=dayScore.values)

dayStatus = player_df.dayScore >= 3
player_df = player_df.assign(dayStatus=dayStatus.values)

valid_hitters = player_df['dayStatus'] == True

player_df.loc[valid_hitters].T

,ID665742,ID592450,ID683011
id,665742,592450,683011
fullName,Juan Soto,Aaron Judge,Anthony Volpe
link,/api/v1/people/665742,/api/v1/people/592450,/api/v1/people/683011
firstName,Juan,Aaron,Anthony
lastName,Soto,Judge,Volpe
primaryNumber,22,99,11
birthDate,1998-10-25,1992-04-26,2001-04-28
currentAge,25,32,23
birthCity,Santo Domingo,Linden,New York
birthStateProvince,NaN,CA,NY
birthCountry,Dominican Republic,USA,USA
height,"6' 2""","6' 7""","5' 9"""
weight,224,282,180
active,True,True,True
primaryPosition,"{'code': '9', 'name': 'Outfielder', 'type': 'O...","{'code': '8', 'name': 'Outfielder', 'type': 'O...","{'code': '6', 'name': 'Shortstop', 'type': 'In..."
useName,Juan,Aaron,Anthony
useLastName,Soto,Judge,Volpe
middleName,Jose,James,Michael
boxscoreName,"Soto, J",Judge,Volpe
gender,M,M,M
isPlayer,True,True,True
isVerified,True,True,True
draftYear,NaN,2013,2019
mlbDebutDate,2018-05-15,2016-08-13,2023-03-30
batSide,"{'code': 'L', 'description': 'Left'}","{'code': 'R', 'description': 'Right'}","{'code': 'R', 'description': 'Right'}"
pitchHand,"{'code': 'L', 'description': 'Left'}","{'code': 'R', 'description': 'Right'}","{'code': 'R', 'description': 'Right'}"
nameFirstLast,Juan Soto,Aaron Judge,Anthony Volpe
nameSlug,juan-soto-665742,aaron-judge-592450,anthony-volpe-683011
firstLastName,Juan Soto,Aaron Judge,Anthony Volpe
lastFirstName,"Soto, Juan","Judge, Aaron","Volpe, Anthony"
lastInitName,"Soto, J","Judge, A","Volpe, A"
initLastName,J Soto,A Judge,A Volpe
fullFMLName,Juan Jose Soto,Aaron James Judge,Anthony Michael Volpe
fullLFMName,"Soto, Juan Jose","Judge, Aaron James","Volpe, Anthony Michael"
strikeZoneTop,3.1,4.05,3.39
strikeZoneBottom,1.5,1.83,1.6
nickName,Soto Pacheco,Baj,NaN
nameTitle,NaN,NaN,NaN
nameSuffix,NaN,NaN,NaN
pronunciation,NaN,NaN,NaN
nameMatrilineal,Pacheco,NaN,NaN
avg,0.311,0.31,0.251
atBats,360.0,358.0,418.0
batScore,3.732,3.699333,3.497267
dayScore,3.732,3.699333,3.497267
dayStatus,True,True,True

In [6]:
HOST = 'https://statsapi.mlb.com'
url = HOST + df.loc[0,'link']
r = requests.get(url=url).json()
player_df = pd.DataFrame(r['gameData']['players'])
player_df_all = pd.DataFrame(['players'])
player_df = player_df.T