## This notebook is to demonstrate how to retrieve game stats for specific teams over a given period of time

In [17]:
import pandas as pd
import requests
import numpy as np
import statsapi
from datetime import datetime, timedelta
TODAY = datetime.today().strftime('%m/%d/%Y')
LAST_YEAR = (datetime.today() - timedelta(days=365)).strftime('%m/%d/%Y')

In [18]:
# Gets one player's stats for one game
data = statsapi.get('person_stats', {'personId' : '665742', 'gamePk' : '745717'})

In [41]:
# Gets games in a certain range
games = statsapi.schedule(start_date=LAST_YEAR,end_date=TODAY,team=143,opponent=121)

In [42]:
# In retrospect, this is not the best way to do this. It was much easier to gather
# data from previous seasons using Savant: https://baseballsavant.mlb.com/leaderboard

In [43]:
for game in games:
    game_data = statsapi.boxscore_data(game['game_id'], timecode=None)
    players = pd.DataFrame(game_data['away']['players'])
    # print(game_data['ID'+str(game['game_id'])])
# for player_id in list(players.keys()):
#     print(players[player_id]['seasonStats'])
players = players.T

In [44]:
players

,person,jerseyNumber,position,status,parentTeamId,stats,seasonStats,gameStatus,allPositions,battingOrder
ID518617,"{'id': 518617, 'fullName': 'Jake Diekman'}",30,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {'runs': 0, 'doubl...","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},[{'abbreviation': 'P'}],NaN
ID620443,"{'id': 620443, 'fullName': 'Luis Torrens'}",13,{'abbreviation': 'C'},{},121,"{'batting': {'runs': 1, 'doubles': 0, 'triples...","{'batting': {'runs': 4, 'doubles': 1, 'triples...",{},[{'abbreviation': 'C'}],900
ID622663,"{'id': 622663, 'fullName': 'Luis Severino'}",40,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},NaN,NaN
ID621438,"{'id': 621438, 'fullName': 'Tyrone Taylor'}",15,{'abbreviation': 'RF'},{},121,"{'batting': {'runs': 1, 'doubles': 0, 'triples...","{'batting': {'runs': 15, 'doubles': 6, 'triple...",{},"[{'abbreviation': 'CF'}, {'abbreviation': 'RF'}]",600
ID621512,"{'id': 621512, 'fullName': 'Tomás Nido'}",3,{'abbreviation': 'C'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 9, 'doubles': 2, 'triples...",{},NaN,NaN
ID640455,"{'id': 640455, 'fullName': 'Sean Manaea'}",59,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},NaN,NaN
ID643446,"{'id': 643446, 'fullName': 'Jeff McNeil'}",1,{'abbreviation': '2B'},{},121,"{'batting': {'runs': 1, 'doubles': 0, 'triples...","{'batting': {'runs': 21, 'doubles': 10, 'tripl...",{},[{'abbreviation': '2B'}],700
ID668901,"{'id': 668901, 'fullName': 'Mark Vientos'}",27,{'abbreviation': '3B'},{},121,"{'batting': {'note': 'b-', 'runs': 0, 'doubles...","{'batting': {'runs': 12, 'doubles': 4, 'triple...",{},"[{'abbreviation': 'PH'}, {'abbreviation': '3B'}]",801
ID683146,"{'id': 683146, 'fullName': 'Brett Baty'}",22,{'abbreviation': '3B'},{},121,"{'batting': {'runs': 0, 'doubles': 0, 'triples...","{'batting': {'runs': 15, 'doubles': 3, 'triple...",{},[{'abbreviation': '3B'}],800
ID578428,"{'id': 578428, 'fullName': 'Jose Iglesias'}",11,{'abbreviation': '3B'},{},121,"{'batting': {'note': '1-', 'runs': 1, 'doubles...","{'batting': {'runs': 4, 'doubles': 2, 'triples...",{},"[{'abbreviation': 'PR'}, {'abbreviation': '3B'}]",802
ID493603,"{'id': 493603, 'fullName': 'Adam Ottavino'}",0,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},NaN,NaN
ID673380,"{'id': 673380, 'fullName': 'Dedniel Núñez'}",72,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {'runs': 1, 'doubl...","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},[{'abbreviation': 'P'}],NaN
ID500779,"{'id': 500779, 'fullName': 'Jose Quintana'}",62,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {'runs': 3, 'doubl...","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},[{'abbreviation': 'P'}],NaN
ID656887,"{'id': 656887, 'fullName': 'Sean Reid-Foley'}",71,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},NaN,NaN
ID502110,"{'id': 502110, 'fullName': 'J.D. Martinez'}",28,{'abbreviation': 'DH'},{},121,"{'batting': {'runs': 0, 'doubles': 0, 'triples...","{'batting': {'runs': 13, 'doubles': 8, 'triple...",{},[{'abbreviation': 'DH'}],400
ID621466,"{'id': 621466, 'fullName': 'DJ Stewart'}",29,{'abbreviation': 'RF'},{},121,"{'batting': {'runs': 0, 'doubles': 0, 'triples...","{'batting': {'runs': 11, 'doubles': 4, 'triple...",{},[{'abbreviation': 'RF'}],500
ID624413,"{'id': 624413, 'fullName': 'Pete Alonso'}",20,{'abbreviation': '1B'},{},121,"{'batting': {'runs': 1, 'doubles': 0, 'triples...","{'batting': {'runs': 37, 'doubles': 16, 'tripl...",{},[{'abbreviation': '1B'}],200
ID656849,"{'id': 656849, 'fullName': 'David Peterson'}",23,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},NaN,NaN
ID516782,"{'id': 516782, 'fullName': 'Starling Marte'}",6,{'abbreviation': 'RF'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 32, 'doubles': 8, 'triple...",{},NaN,NaN
ID596019,"{'id': 596019, 'fullName': 'Francisco Lindor'}",12,{'abbreviation': 'SS'},{},121,"{'batting': {'runs': 0, 'doubles': 0, 'triples...","{'batting': {'runs': 37, 'doubles': 15, 'tripl...",{},[{'abbreviation': 'SS'}],100
ID664056,"{'id': 664056, 'fullName': 'Harrison Bader'}",44,{'abbreviation': 'CF'},{},121,"{'batting': {'note': 'a-', 'runs': 0, 'doubles...","{'batting': {'runs': 21, 'doubles': 9, 'triple...",{},"[{'abbreviation': 'PH'}, {'abbreviation': 'CF'}]",501
ID607043,"{'id': 607043, 'fullName': 'Brandon Nimmo'}",9,{'abbreviation': 'LF'},{},121,"{'batting': {'runs': 1, 'doubles': 1, 'triples...","{'batting': {'runs': 32, 'doubles': 11, 'tripl...",{},[{'abbreviation': 'LF'}],300
ID622098,"{'id': 622098, 'fullName': 'Drew Smith'}",33,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {'note': '(S, 2)',...","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},[{'abbreviation': 'P'}],NaN
ID664849,"{'id': 664849, 'fullName': 'Danny Young'}",81,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {'runs': 0, 'doubl...","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},[{'abbreviation': 'P'}],NaN
ID657585,"{'id': 657585, 'fullName': 'Reed Garrett'}",75,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {'note': '(W, 6-2)...","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},[{'abbreviation': 'P'}],NaN
ID605288,"{'id': 605288, 'fullName': 'Adrian Houser'}",35,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},NaN,NaN
ID656731,"{'id': 656731, 'fullName': 'Tylor Megill'}",38,{'abbreviation': 'P'},{},121,"{'batting': {}, 'pitching': {}}","{'batting': {'runs': 0, 'doubles': 0, 'triples...",{},NaN,NaN