In [262]:
import pandas as pd
import requests
import numpy as np
import statsapi

In [263]:
url = 'http://statsapi.mlb.com/api/v1/schedule/games/?sportId=1'
r = requests.get(url=url).json()
dates = r['dates'][0]['games']
df = pd.DataFrame(dates)
df

,gamePk,gameGuid,link,gameType,season,gameDate,officialDate,status,teams,venue,...,dayNight,scheduledInnings,reverseHomeAwayStatus,inningBreakLength,gamesInSeries,seriesGameNumber,seriesDescription,recordSource,ifNecessary,ifNecessaryDescription
0,746614,6bd79b38-55bb-4164-995f-90a53079ef33,/api/v1.1/game/746614/feed/live,R,2024,2024-07-23T22:40:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 50, 'losses...","{'id': 5, 'name': 'Progressive Field', 'link':...",...,night,9,False,120,4,2,Regular Season,S,N,Normal Game
1,745475,aad2fd45-097a-4fb0-a801-826c9b3f50ad,/api/v1.1/game/745475/feed/live,R,2024,2024-07-23T22:40:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 52, 'losses...","{'id': 31, 'name': 'PNC Park', 'link': '/api/v...",...,night,9,False,120,3,2,Regular Season,S,N,Normal Game
2,746036,94181dbc-ecca-4fd3-8c65-64eab678a8cd,/api/v1.1/game/746036/feed/live,R,2024,2024-07-23T22:40:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 60, 'losses...","{'id': 4169, 'name': 'loanDepot park', 'link':...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
3,744828,429e512a-91e3-4daf-be0a-39f8f6d271f4,/api/v1.1/game/744828/feed/live,R,2024,2024-07-23T22:45:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 52, 'losses...","{'id': 3309, 'name': 'Nationals Park', 'link':...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
4,745715,2080e423-2257-437a-ac27-96ec5a77623f,/api/v1.1/game/745715/feed/live,R,2024,2024-07-23T23:05:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 51, 'losses...","{'id': 3313, 'name': 'Yankee Stadium', 'link':...",...,night,9,False,145,2,1,Regular Season,S,N,Normal Game
5,744904,9448e12c-07ab-4cc7-aac2-990ba2f00bea,/api/v1.1/game/744904/feed/live,R,2024,2024-07-23T23:07:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 50, 'losses...","{'id': 14, 'name': 'Rogers Centre', 'link': '/...",...,night,9,False,120,3,1,Regular Season,S,N,Normal Game
6,747090,f8c05529-1a3e-45d8-82b1-782cd7f749be,/api/v1.1/game/747090/feed/live,R,2024,2024-07-23T23:20:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 48, 'losses...","{'id': 4705, 'name': 'Truist Park', 'link': '/...",...,night,9,False,120,3,2,Regular Season,S,N,Normal Game
7,745878,99415897-4394-40f7-b051-339653ac4c67,/api/v1.1/game/745878/feed/live,R,2024,2024-07-23T23:40:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 63, 'losses...","{'id': 3312, 'name': 'Target Field', 'link': '...",...,night,9,False,120,3,2,Regular Season,S,N,Normal Game
8,744985,61262b76-01ac-4bd4-a595-e3bae5d1307e,/api/v1.1/game/744985/feed/live,R,2024,2024-07-24T00:05:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 27, 'losses...","{'id': 5325, 'name': 'Globe Life Field', 'link...",...,night,9,False,120,4,2,Regular Season,S,N,Normal Game
9,746848,95ff96cc-74d1-4472-b7ba-4dcc9227e9e4,/api/v1.1/game/746848/feed/live,R,2024,2024-07-24T00:05:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 57, 'losses...","{'id': 17, 'name': 'Wrigley Field', 'link': '/...",...,night,9,False,120,3,2,Regular Season,S,N,Normal Game
10,746281,99fc9351-1b96-451a-ba25-d9293dde0d77,/api/v1.1/game/746281/feed/live,R,2024,2024-07-24T00:10:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 51, 'losses...","{'id': 7, 'name': 'Kauffman Stadium', 'link': ...",...,night,9,False,120,3,2,Regular Season,S,N,Normal Game
11,746524,786fdb9b-3ef1-4525-b9cc-5ca747cba6a3,/api/v1.1/game/746524/feed/live,R,2024,2024-07-24T00:40:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 53, 'losses...","{'id': 19, 'name': 'Coors Field', 'link': '/ap...",...,night,9,False,120,3,2,Regular Season,S,N,Normal Game
12,745632,07ba878b-6194-472d-84ed-393d5e23b190,/api/v1.1/game/745632/feed/live,R,2024,2024-07-24T01:40:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 52, 'losses...","{'id': 10, 'name': 'Oakland Coliseum', 'link':...",...,night,9,False,120,3,2,Regular Season,S,N,Normal Game
13,745227,6339eba6-5788-415f-aec6-13d9f9d362ec,/api/v1.1/game/745227/feed/live,R,2024,2024-07-24T01:40:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 43, 'losses...","{'id': 680, 'name': 'T-Mobile Park', 'link': '...",...,night,9,False,120,3,2,Regular Season,S,N,Normal Game
14,746118,c33054bd-195f-4f0f-a188-e793aa351c22,/api/v1.1/game/746118/feed/live,R,2024,2024-07-24T02:10:00Z,2024-07-23,"{'abstractGameState': 'Preview', 'codedGameSta...","{'away': {'leagueRecord': {'wins': 48, 'losses...","{'id': 22, 'name': 'Dodger Stadium', 'link': '...",...,night,9,False,120,4,2,Regular Season,S,N,Normal Game

In [267]:
HOST = 'https://statsapi.mlb.com'
url = HOST + df.loc[0,'link']
r = requests.get(url=url).json()
player_df = pd.DataFrame(r['gameData']['players'])
player_df_all = pd.DataFrame(['players'])
player_df = player_df.T
# player_df.T
gameteams_df = pd.DataFrame(r['gameData']['teams'])
player_df

,id,fullName,link,firstName,lastName,primaryNumber,birthDate,currentAge,birthCity,birthStateProvince,...,firstLastName,lastFirstName,lastInitName,initLastName,fullFMLName,fullLFMName,strikeZoneTop,strikeZoneBottom,pronunciation,nameMatrilineal
ID647304,647304,Josh Naylor,/api/v1/people/647304,Joshua-Douglas,Naylor,22,1997-06-22,27,Mississauga,ON,...,Josh Naylor,"Naylor, Josh","Naylor, J",J Naylor,Joshua-Douglas James Naylor,"Naylor, Joshua-Douglas James",3.15,1.51,NaN,NaN
ID669373,669373,Tarik Skubal,/api/v1/people/669373,Tarik,Skubal,29,1996-11-20,27,Hayward,CA,...,Tarik Skubal,"Skubal, Tarik","Skubal, T",T Skubal,Tarik Daniel Skubal,"Skubal, Tarik Daniel",3.49,1.601,Tare-ick sku-ble,NaN
ID689225,689225,Beau Brieske,/api/v1/people/689225,Beau,Brieske,4,1998-04-04,26,Chandler,AZ,...,Beau Brieske,"Brieske, Beau","Brieske, B",B Brieske,Beau Conner Brieske,"Brieske, Beau Conner",3.49,1.601,NaN,NaN
ID687922,687922,Easton Lucas,/api/v1/people/687922,Easton,Lucas,57,1996-09-23,27,Thousand Oaks,CA,...,Easton Lucas,"Lucas, Easton","Lucas, E",E Lucas,Easton James Lucas,"Lucas, Easton James",3.549,1.627,NaN,NaN
ID682985,682985,Riley Greene,/api/v1/people/682985,Riley,Greene,31,2000-09-28,23,Orlando,FL,...,Riley Greene,"Greene, Riley","Greene, R",R Greene,Riley Alan Greene,"Greene, Riley Alan",3.73,1.71,NaN,NaN
ID595978,595978,Austin Hedges,/api/v1/people/595978,Austin,Hedges,27,1992-08-18,31,San Juan Capistrano,CA,...,Austin Hedges,"Hedges, Austin","Hedges, A",A Hedges,Austin Charles Hedges,"Hedges, Austin Charles",3.3,1.49,NaN,NaN
ID663947,663947,Tyler Holton,/api/v1/people/663947,Weston,Holton,87,1996-06-13,28,Tallahassee,FL,...,Tyler Holton,"Holton, Tyler","Holton, T",T Holton,Weston Tyler Holton,"Holton, Weston Tyler",3.467,1.589,NaN,NaN
ID471911,471911,Carlos Carrasco,/api/v1/people/471911,Carlos,Carrasco,59,1987-03-21,37,Barquisimeto,NaN,...,Carlos Carrasco,"Carrasco, Carlos","Carrasco, C",C Carrasco,Carlos Luis Carrasco,"Carrasco, Carlos Luis",3.549,1.627,cuh-RAZZ-coh,NaN
ID686823,686823,Will Brennan,/api/v1/people/686823,William,Brennan,17,1998-02-02,26,Colorado Springs,CO,...,Will Brennan,"Brennan, Will","Brennan, W",W Brennan,William Daniel Brennan,"Brennan, William Daniel",3.29,1.55,NaN,NaN
ID661403,661403,Emmanuel Clase,/api/v1/people/661403,Emmanuel,Clase,48,1998-03-18,26,Rio San Juan,NaN,...,Emmanuel Clase,"Clase, Emmanuel","Clase, E",E Clase,Emmanuel Clase,"Clase, Emmanuel",3.467,1.589,clas-A,De La Cruz
ID658648,658648,Pedro Avila,/api/v1/people/658648,Pedro,Avila,60,1997-01-14,27,Caracas,NaN,...,Pedro Avila,"Avila, Pedro","Avila, P",P Avila,Pedro Manuel Avila,"Avila, Pedro Manuel",3.33,1.48,AH-vee-la,Puentes
ID608348,608348,Carson Kelly,/api/v1/people/608348,Carson,Kelly,15,1994-07-14,30,Chicago,IL,...,Carson Kelly,"Kelly, Carson","Kelly, C",C Kelly,Carson Franklin Kelly,"Kelly, Carson Franklin",3.36,1.56,NaN,NaN
ID665926,665926,Andrés Giménez,/api/v1/people/665926,Andrés,Giménez,0,1998-09-04,25,Barquisimeto,NaN,...,Andrés Giménez,"Giménez, Andrés","Giménez, A",A Gimenez,Andrés Alfonso Giménez,"Giménez, Andrés Alfonso",3.23,1.47,he-MEN-ez,Osorio
ID570482,570482,Gio Urshela,/api/v1/people/570482,Giovanny,Urshela,13,1991-10-11,32,Cartagena,NaN,...,Gio Urshela,"Urshela, Gio","Urshela, G",G Urshela,Giovanny Urshela,"Urshela, Giovanny",3.51,1.63,urr-SHELL-ah,NaN
ID676632,676632,Bligh Madris,/api/v1/people/676632,Bligh,Madris,40,1996-02-29,28,Las Vegas,NV,...,Bligh Madris,"Madris, Bligh","Madris, B",B Madris,Bligh John Madris,"Madris, Bligh John",3.36,1.57,NaN,NaN
ID656427,656427,Jack Flaherty,/api/v1/people/656427,Jack,Flaherty,9,1995-10-15,28,Burbank,CA,...,Jack Flaherty,"Flaherty, Jack","Flaherty, J",J Flaherty,Jack Rafe Flaherty,"Flaherty, Jack Rafe",3.48,1.62,NaN,NaN
ID675540,675540,Xzavion Curry,/api/v1/people/675540,Xzavion,Curry,44,1998-07-27,25,Orangeburg,SC,...,Xzavion Curry,"Curry, Xzavion","Curry, X",X Curry,Xzavion Rashan Curry,"Curry, Xzavion Rashan",3.371,1.535,NaN,NaN
ID592192,592192,Mark Canha,/api/v1/people/592192,Mark,Canha,21,1989-02-15,35,San Jose,CA,...,Mark Canha,"Canha, Mark","Canha, M",M Canha,Mark David Canha,"Canha, Mark David",3.32,1.44,CAN-uh,NaN
ID671345,671345,Jason Foley,/api/v1/people/671345,Jason,Foley,68,1995-11-01,28,Manhasset,NY,...,Jason Foley,"Foley, Jason","Foley, J",J Foley,Jason Joseph Foley,"Foley, Jason Joseph",3.549,1.627,NaN,NaN
ID666310,666310,Bo Naylor,/api/v1/people/666310,Noah,Naylor,23,2000-02-21,24,Mississauga,ON,...,Bo Naylor,"Naylor, Bo","Naylor, B",B Naylor,Noah G. Naylor,"Naylor, Noah G.",3.25,1.53,NaN,NaN
ID681807,681807,David Fry,/api/v1/people/681807,David,Fry,6,1995-11-20,28,Colleyville,TX,...,David Fry,"Fry, David","Fry, D",D Fry,David Fry,"Fry, David",3.35,1.53,NaN,NaN
ID671922,671922,Cade Smith,/api/v1/people/671922,Cade,Smith,36,1999-05-09,25,Vancouver,BC,...,Cade Smith,"Smith, Cade","Smith, C",C Smith,Cade Jared Benjamin Smith,"Smith, Cade Jared Benjamin",3.575,1.681,NaN,NaN
ID628317,628317,Kenta Maeda,/api/v1/people/628317,Kenta,Maeda,18,1988-04-11,36,Osaka,NaN,...,Kenta Maeda,"Maeda, Kenta","Maeda, K",K Maeda,Kenta Maeda,"Maeda, Kenta",3.411,1.565,mah-EH-dah,NaN
ID608070,608070,José Ramírez,/api/v1/people/608070,José,Ramírez,11,1992-09-17,31,Bani,NaN,...,José Ramírez,"Ramírez, José","Ramírez, J",J Ramírez,José Enrique Ramírez,"Ramírez, José Enrique",3.42,1.64,NaN,NaN
ID680757,680757,Steven Kwan,/api/v1/people/680757,Steven,Kwan,38,1997-09-05,26,Los Gatos,CA,...,Steven Kwan,"Kwan, Steven","Kwan, S",S Kwan,Steven Robert Kwan,"Kwan, Steven Robert",3.23,1.5,NaN,NaN
ID682657,682657,Angel Martínez,/api/v1/people/682657,Angel,Martínez,1,2002-01-27,22,Santo Domingo,NaN,...,Angel Martínez,"Martínez, Angel","Martínez, A",A Martínez,Angel Martínez,"Martínez, Angel",3.23,1.46,NaN,NaN
ID663837,663837,Matt Vierling,/api/v1/people/663837,Matthew,Vierling,8,1996-09-16,27,St. Louis,MO,...,Matt Vierling,"Vierling, Matt","Vierling, M",M Vierling,Matthew Gregory Vierling,"Vierling, Matthew Gregory",3.48,1.63,VEER-ling,NaN
ID690993,690993,Colt Keith,/api/v1/people/690993,Colten,Keith,33,2001-08-14,22,Zanesville,OH,...,Colt Keith,"Keith, Colt","Keith, C",C Keith,Colten Thomas Keith,"Keith, Colten Thomas",3.34,1.55,NaN,NaN
ID669234,669234,Justyn-Henry Malloy,/api/v1/people/669234,Justyn-Henry,Malloy,44,2000-02-19,24,New York,NY,...,Justyn-Henry Malloy,"Malloy, Justyn-Henry","Malloy, J",J Malloy,Justyn-Henry Conrad Malloy,"Malloy, Justyn-Henry Conrad",3.52,1.62,NaN,NaN
ID656716,656716,Zach McKinstry,/api/v1/people/656716,Zachary,McKinstry,39,1995-04-29,29,Toledo,OH,...,Zach McKinstry,"McKinstry, Zach","McKinstry, Z",Z McKinstry,Zachary McKinstry,"McKinstry, Zachary",3.5,1.6,muh-KIN-stry,NaN
ID680704,680704,Nick Sandlin,/api/v1/people/680704,Nick,Sandlin,52,1997-01-10,27,Evans,GA,...,Nick Sandlin,"Sandlin, Nick","Sandlin, N",N Sandlin,Nick Howard Sandlin,"Sandlin, Nick Howard",3.319,1.513,NaN,NaN
ID571946,571946,Shelby Miller,/api/v1/people/571946,Shelby,Miller,7,1990-10-10,33,Round Rock,TX,...,Shelby Miller,"Miller, Shelby","Miller, S",S Miller,Shelby Charles Miller,"Miller, Shelby Charles",3.49,1.601,NaN,NaN
ID594902,594902,Ben Lively,/api/v1/people/594902,Edward,Lively,39,1992-03-05,32,Pensacola,FL,...,Ben Lively,"Lively, Ben","Lively, B",B Lively,Edward Bennett Lively,"Lively, Edward Bennett",3.549,1.627,NaN,NaN
ID595879,595879,Javier Báez,/api/v1/people/595879,Ednel,Báez,28,1992-12-01,31,Bayamon,NaN,...,Javier Báez,"Báez, Javier","Báez, J",J Báez,Ednel Javier Báez,"Báez, Ednel Javier",3.48,1.59,NaN,NaN
ID605130,605130,Scott Barlow,/api/v1/people/605130,Scott,Barlow,58,1992-12-18,31,New London,CT,...,Scott Barlow,"Barlow, Scott","Barlow, S",S Barlow,Scott A. Barlow,"Barlow, Scott A.",3.49,1.601,NaN,NaN
ID605177,605177,Andrew Chafin,/api/v1/people/605177,Andrew,Chafin,17,1990-06-17,34,Kettering,OH,...,Andrew Chafin,"Chafin, Andrew","Chafin, A",A Chafin,Andrew Gregory Chafin,"Chafin, Andrew Gregory",3.467,1.589,CHAY-fin,NaN
ID682177,682177,Daniel Schneemann,/api/v1/people/682177,Daniel,Schneemann,10,1997-01-23,27,San Diego,CA,...,Daniel Schneemann,"Schneemann, Daniel","Schneemann, D",D Schneemann,Daniel Schneemann,"Schneemann, Daniel",3.41,1.65,NaN,NaN
ID678877,678877,Jhonkensy Noel,/api/v1/people/678877,Jhonkensy,Noel,43,2001-07-15,23,San Pedro de Macoris,NaN,...,Jhonkensy Noel,"Noel, Jhonkensy","Noel, J",J Noel,Jhonkensy Noel,"Noel, Jhonkensy",3.52,1.72,NaN,Do Lee
ID677587,677587,Brayan Rocchio,/api/v1/people/677587,Brayan,Rocchio,4,2001-01-13,23,Caracas,NaN,...,Brayan Rocchio,"Rocchio, Brayan","Rocchio, B",B Rocchio,Brayan Hommy Rocchio,"Rocchio, Brayan Hommy",3.14,1.45,NaN,Zambrano
ID672456,672456,Keider Montero,/api/v1/people/672456,Keider,Montero,54,2000-07-06,24,Santa Teresa del Tuy,NaN,...,Keider Montero,"Montero, Keider","Montero, K",K Montero,Keider Eduardo Montero,"Montero, Keider Eduardo",3.411,1.565,NaN,Martinez
ID671289,671289,Tyler Freeman,/api/v1/people/671289,Tyler,Freeman,2,1999-05-21,25,Rancho Cucamonga,CA,...,Tyler Freeman,"Freeman, Tyler","Freeman, T",T Freeman,Tyler Andrew Freeman,"Freeman, Tyler Andrew",3.24,1.41,NaN,NaN
ID668670,668670,Jake Rogers,/api/v1/people/668670,Jacob,Rogers,34,1995-04-18,29,Canyon,TX,...,Jake Rogers,"Rogers, Jake","Rogers, J",J Rogers,Jacob Ray Rogers,"Rogers, Jacob Ray",3.34,1.48,NaN,NaN
ID666214,666214,Joey Wentz,/api/v1/people/666214,Joseph,Wentz,43,1997-10-06,26,Lawrence,KS,...,Joey Wentz,"Wentz, Joey","Wentz, J",J Wentz,Joseph Barrett Wentz,"Wentz, Joseph Barrett",3.575,1.681,NaN,NaN
ID628451,628451,Andy Ibáñez,/api/v1/people/628451,Andy,Ibáñez,77,1993-04-03,31,Havana,NaN,...,Andy Ibáñez,"Ibáñez, Andy","Ibáñez, A",A Ibáñez,Andy Ibáñez,"Ibáñez, Andy",3.2,1.48,ee-BAHN-yez,Velazquez
ID668909,668909,Gavin Williams,/api/v1/people/668909,Gavin,Williams,32,1999-07-26,24,Fayetteville,NC,...,Gavin Williams,"Williams, Gavin","Williams, G",G Williams,Gavin Scott Williams,"Williams, Gavin Scott",3.656,1.677,NaN,NaN
ID657265,657265,Peter Strzelecki,/api/v1/people/657265,Peter,Strzelecki,34,1994-10-24,29,Queens,NY,...,Peter Strzelecki,"Strzelecki, Peter","Strzelecki, P",P Strzelecki,Peter J. Strzelecki,"Strzelecki, Peter J.",3.467,1.589,NaN,NaN
ID683769,683769,Hunter Gaddis,/api/v1/people/683769,Hunter,Gaddis,33,1998-04-09,26,Canton,GA,...,Hunter Gaddis,"Gaddis, Hunter","Gaddis, H",H Gaddis,Hunter Reid Gaddis,"Gaddis, Hunter Reid",3.656,1.677,NaN,NaN
ID682120,682120,Tim Herrin,/api/v1/people/682120,Tim,Herrin,29,1996-10-08,27,Terre Haute,IN,...,Tim Herrin,"Herrin, Tim","Herrin, T",T Herrin,Tim Edward Herrin,"Herrin, Tim Edward",3.656,1.677,NaN,NaN
ID676440,676440,Tanner Bibee,/api/v1/people/676440,Tanner,Bibee,28,1999-03-05,25,Mission Viejo,CA,...,Tanner Bibee,"Bibee, Tanner","Bibee, T",T Bibee,Tanner Hayes Bibee,"Bibee, Tanner Hayes",3.467,1.589,NaN,NaN
ID676684,676684,Will Vest,/api/v1/people/676684,William,Vest,19,1995-06-06,29,Houston,TX,...,Will Vest,"Vest, Will","Vest, W",W Vest,William Lane Vest,"Vest, William Lane",3.371,1.535,NaN,NaN
ID672761,672761,Wenceel Pérez,/api/v1/people/672761,Wenceel,Pérez,46,1999-10-30,24,Azua,NaN,...,Wenceel Pérez,"Pérez, Wenceel","Pérez, W",W Pérez,Wenceel Xavier Pérez,"Pérez, Wenceel Xavier",3.21,1.45,NaN,Vargas
ID656412,656412,Alex Faedo,/api/v1/people/656412,Alexander,Faedo,49,1995-11-12,28,Tampa,FL,...,Alex Faedo,"Faedo, Alex","Faedo, A",A Faedo,Alexander Michael Faedo,"Faedo, Alexander Michael",3.575,1.681,fie-a-dough,NaN

In [265]:
def get_hitsPer9(player_id):
    player = statsapi.player_stat_data(int(player_id), group= "pitching", type="season", sportId=1)
    if player['position'] != 'P':
        return 0
    return float(player['stats'][0]['stats']['hitsPer9Inn'])

def get_inningsPitched(player_id):
    player = statsapi.player_stat_data(int(player_id), group= "pitching", type="season", sportId=1)
    if player['position'] != 'P':
        return 0
    return float(player['stats'][0]['stats']['inningsPitched'])

def get_gamesStarted(player_id):
    player = statsapi.player_stat_data(int(player_id), group= "pitching", type="season", sportId=1)
    if player['position'] != 'P':
        return 0
    return float(player['stats'][0]['stats']['gamesStarted'])

player_hitsPer9 = player_df.id.apply(get_hitsPer9)
player_df = player_df.assign(hitsPer9=player_hitsPer9.values)

player_inningsPitched = player_df.id.apply(get_inningsPitched)
player_df = player_df.assign(inningsPitched=player_inningsPitched.values)

player_gamesStarted = player_df.id.apply(get_gamesStarted)
player_df = player_df.assign(gamesStarted=player_gamesStarted.values)

In [266]:
pitchers = player_df['hitsPer9'] != 0
pitcher_df = player_df.loc[pitchers]

startingPitchers = player_df['gamesStarted'] != 0
startingPitcher_df = player_df.loc[startingPitchers]
startingPitcher_df.sort_values(by = ['hitsPer9'], ascending = True)

,id,fullName,link,firstName,lastName,primaryNumber,birthDate,currentAge,birthCity,birthStateProvince,...,initLastName,fullFMLName,fullLFMName,strikeZoneTop,strikeZoneBottom,pronunciation,nameMatrilineal,hitsPer9,inningsPitched,gamesStarted
ID663947,663947,Tyler Holton,/api/v1/people/663947,Weston,Holton,87,1996-06-13,28,Tallahassee,FL,...,T Holton,Weston Tyler Holton,"Holton, Weston Tyler",3.467,1.589,NaN,NaN,6.00,54.0,1.0
ID669373,669373,Tarik Skubal,/api/v1/people/669373,Tarik,Skubal,29,1996-11-20,27,Hayward,CA,...,T Skubal,Tarik Daniel Skubal,"Skubal, Tarik Daniel",3.49,1.601,Tare-ick sku-ble,NaN,6.66,123.0,20.0
ID656427,656427,Jack Flaherty,/api/v1/people/656427,Jack,Flaherty,9,1995-10-15,28,Burbank,CA,...,J Flaherty,Jack Rafe Flaherty,"Flaherty, Jack Rafe",3.48,1.62,NaN,NaN,7.15,100.2,17.0
ID656412,656412,Alex Faedo,/api/v1/people/656412,Alexander,Faedo,49,1995-11-12,28,Tampa,FL,...,A Faedo,Alexander Michael Faedo,"Faedo, Alexander Michael",3.575,1.681,fie-a-dough,NaN,7.29,45.2,1.0
ID676440,676440,Tanner Bibee,/api/v1/people/676440,Tanner,Bibee,28,1999-03-05,25,Mission Viejo,CA,...,T Bibee,Tanner Hayes Bibee,"Bibee, Tanner Hayes",3.467,1.589,NaN,NaN,7.56,110.2,20.0
ID689225,689225,Beau Brieske,/api/v1/people/689225,Beau,Brieske,4,1998-04-04,26,Chandler,AZ,...,B Brieske,Beau Conner Brieske,"Brieske, Beau Conner",3.49,1.601,NaN,NaN,8.10,33.1,1.0
ID594902,594902,Ben Lively,/api/v1/people/594902,Edward,Lively,39,1992-03-05,32,Pensacola,FL,...,B Lively,Edward Bennett Lively,"Lively, Edward Bennett",3.549,1.627,NaN,NaN,8.10,93.1,17.0
ID672456,672456,Keider Montero,/api/v1/people/672456,Keider,Montero,54,2000-07-06,24,Santa Teresa del Tuy,NaN,...,K Montero,Keider Eduardo Montero,"Montero, Keider Eduardo",3.411,1.565,NaN,Martinez,9.66,31.2,5.0
ID471911,471911,Carlos Carrasco,/api/v1/people/471911,Carlos,Carrasco,59,1987-03-21,37,Barquisimeto,NaN,...,C Carrasco,Carlos Luis Carrasco,"Carrasco, Carlos Luis",3.549,1.627,cuh-RAZZ-coh,NaN,9.85,91.1,18.0
ID675540,675540,Xzavion Curry,/api/v1/people/675540,Xzavion,Curry,44,1998-07-27,25,Orangeburg,SC,...,X Curry,Xzavion Rashan Curry,"Curry, Xzavion Rashan",3.371,1.535,NaN,NaN,9.87,17.1,3.0
ID668909,668909,Gavin Williams,/api/v1/people/668909,Gavin,Williams,32,1999-07-26,24,Fayetteville,NC,...,G Williams,Gavin Scott Williams,"Williams, Gavin Scott",3.656,1.677,NaN,NaN,10.00,18.0,4.0
ID628317,628317,Kenta Maeda,/api/v1/people/628317,Kenta,Maeda,18,1988-04-11,36,Osaka,NaN,...,K Maeda,Kenta Maeda,"Maeda, Kenta",3.411,1.565,mah-EH-dah,NaN,10.72,71.1,16.0

In [219]:
away_id = int(gameteams_df['away']['id'])
home_id = int(gameteams_df['home']['id'])
print(statsapi.team_leaders(away_id,'gamesStarted',limit=3,season=2024))

Rank Name                 Value
 1   Tarik Skubal          20
 2   Reese Olson           19
 3   Jack Flaherty         17

In [220]:
away_players = statsapi.lookup_player(away_id)
away_avg_HP9 = 0.0
num_away_pitchers = 0.0

for index in range (0, len(away_players)):
    guy = away_players[index]
    if int(guy['primaryPosition']['code']) == 1:
        dude = statsapi.player_stat_data(guy['id'], group= "pitching", type="season", sportId=1)
        if dude['stats'][0]['stats']['gamesStarted'] >= 0:
            away_avg_HP9 += float(dude['stats'][0]['stats']['hitsPer9Inn'])
            num_away_pitchers += 1
away_avg_HP9 /= num_away_pitchers
away_avg_HP9

9.186666666666666

In [221]:
player = statsapi.player_stat_data(694973, group= "pitching", type="season", sportId=1)
# player

In [222]:
home_players = statsapi.lookup_player(home_id)
home_avg_HP9 = 0.0
num_home_pitchers = 0.0

for index in range (0, len(home_players)):
    guy = home_players[index]
    if int(guy['primaryPosition']['code']) == 1:
        dude = statsapi.player_stat_data(guy['id'], group= "pitching", type="season", sportId=1)
        if dude['stats'][0]['stats']['gamesStarted'] >= 17:
            home_avg_HP9 += float(dude['stats'][0]['stats']['hitsPer9Inn'])
            num_home_pitchers += 1
home_avg_HP9 /= num_home_pitchers
home_avg_HP9

8.955

In [282]:
def get_avg(player_id):
    player = statsapi.player_stat_data(int(player_id), group= "hitting", type="season", sportId=1)
    if player['position'] == 'P':
        return 0
    return float(player['stats'][0]['stats']['avg'])

def get_atBats(player_id):
    player = statsapi.player_stat_data(int(player_id), group= "hitting", type="season", sportId=1)
    if player['position'] == 'P':
        return 0
    return float(player['stats'][0]['stats']['atBats']) 


averages = player_df.id.apply(get_avg)
player_df = player_df.assign(avg=averages.values)

player_atBats = player_df.id.apply(get_atBats)
player_df = player_df.assign(atBats=player_atBats.values)

# player_df

In [281]:
batScore = player_df.avg * player_df.atBats / 30
player_df = player_df.assign(batScore=batScore.values)

dayScore = player_df.batScore * 0
player_df = player_df.assign(dayScore=dayScore.values)

oppHP9 = player_df.id * 0
player_df = player_df.assign(oppHP9=oppHP9.values)

In [260]:
s = HOST + '/api/v1/schedule?sportId=1&hydrate=probablePitcher&startDate=2024-07-23&endDate=2024-07-23'
t = requests.get(url=s).json()
t_df = pd.DataFrame(t['dates'][0]['games'])
# print(t_df['teams'][1]['home']['probablePitcher']['id'])
print(t_df['teams'][1]['home'].get('probablePitcher'))
home_pitcher_id = t_df['teams'][1]['home']['probablePitcher']['id']
home_pitcher = player_df.loc[player_df['id'] == home_pitcher_id]

{'id': 694973, 'fullName': 'Paul Skenes', 'link': '/api/v1/people/694973'}

Empty DataFrame
Columns: [id, fullName, link, firstName, lastName, primaryNumber, birthDate, currentAge, birthCity, birthStateProvince, birthCountry, height, weight, active, primaryPosition, useName, useLastName, middleName, boxscoreName, nickName, gender, isPlayer, isVerified, draftYear, mlbDebutDate, batSide, pitchHand, nameFirstLast, nameSlug, firstLastName, lastFirstName, lastInitName, initLastName, fullFMLName, fullLFMName, strikeZoneTop, strikeZoneBottom, pronunciation, nameMatrilineal, hitsPer9, inningsPitched, gamesStarted, avg, atBats, batScore, oppHP9, dayScore]
Index: []

[0 rows x 47 columns]

In [274]:
for game in range (0, len(t_df)):
    url = HOST + df.loc[game,'link']
    r = requests.get(url=url).json()
    gameteams_df = pd.DataFrame(r['gameData']['teams'])
    player_df = pd.DataFrame(r['gameData']['players'])
    player_df = player_df.T

    def get_avg(player_id):
        player = statsapi.player_stat_data(int(player_id), group= "hitting", type="season", sportId=1)
        if player['position'] == 'P':
            return 0
        return float(player['stats'][0]['stats']['avg'])

    def get_atBats(player_id):
        player = statsapi.player_stat_data(int(player_id), group= "hitting", type="season", sportId=1)
        if player['position'] == 'P':
            return 0
        return float(player['stats'][0]['stats']['atBats'])

    def get_hitsPer9(player_id):
        player = statsapi.player_stat_data(int(player_id), group= "pitching", type="season", sportId=1)
        if player['position'] != 'P':
            return 0
        return float(player['stats'][0]['stats']['hitsPer9Inn'])
    
    averages = player_df.id.apply(get_avg)
    player_df = player_df.assign(avg=averages.values)
    
    player_atBats = player_df.id.apply(get_atBats)
    player_df = player_df.assign(atBats=player_atBats.values)

    player_hitsPer9 = player_df.id.apply(get_hitsPer9)
    player_df = player_df.assign(hitsPer9=player_hitsPer9.values)

    oppHP9 = player_df.id * 0
    player_df = player_df.assign(oppHP9=oppHP9.values)

IndexError: list index out of range

### The code below iterates through all of today's games and applies the HP9 of the opposing pitcher to the dayScore of the hitters

In [ ]:
for game in range (0, len(t_df)):
    url = HOST + df.loc[game,'link']
    r = requests.get(url=url).json()
    gameteams_df = pd.DataFrame(r['gameData']['teams'])
    player_df = pd.DataFrame(r['gameData']['players'])
    player_df = player_df.T

    away_pitcher_id = t_df['teams'][game]['away']['probablePitcher']['id']
    away_pitcher = player_df.loc[player_df['id'] == away_pitcher_id]
    away_HP9 = float(away_pitcher['hitsPer9'].iloc[0])
    
    home_pitcher_id = t_df['teams'][game]['home']['probablePitcher']['id']
    home_pitcher = player_df.loc[player_df['id'] == home_pitcher_id]
    home_HP9 = float(home_pitcher['hitsPer9'].iloc[0])

    for index in range (0, len(away_players)):
        guy_id = away_players[index]['id']
        player_df.loc[player_df['id'] == guy_id, 'oppHP9'] = home_HP9
    for index in range (0, len(home_players)):
        guy_id = home_players[index]['id']
        player_df.loc[player_df['id'] == guy_id, 'oppHP9'] = away_HP9

    
player_df.T

In [ ]:
batScore = player_df.avg * player_df.atBats / 30
player_df = player_df.assign(batScore=batScore.values)

dayScore = player_df.batScore + player_df.oppHP9
player_df = player_df.assign(dayScore=dayScore.values)